name: run security Scan

on:
  schedule:
    - cron: '0 4 * * *' # Execution quotidienne à 2h du matin UTC
  push:
    branches:
      - main

jobs:
  security_gate:
    uses: ZeroDay-Cyber-Academy/all-reusables-workflows/.github/workflows/security-reusable-gate.yml@v1
