name: Security SAST scan 

on:
  push:
    branches:
      - main
      - develop
      - preprod

jobs:
  semgrep:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read

    steps:
      - name: List files
        run: ls -la

      - name: Checkout du code
        uses: actions/checkout@v4

      - name: List files 2
        run: ls -la

      - name: Setup Python
        run: apt install python
      
